### PR TITLE
written test for the issue anf it is failing

### LINKED ISSUE #22: Checkout - Verify Your cart shows correct products

### PR DESCRIPTION
**Pull request by BarnaliD**
Test is failing ,addTocart button is not clicking

### CODE REVIEW

**Comment by BarnaliD** [comment]
Cleaned the code and it works now

File: src/test/java/CheckWebshopStepDefinition.java [hunk 1]
```diff
@@ -141,6 +149,52 @@ public void theHeadingTextShouldBe(String headingType, String expectedText) {
...
+     System.out.println("User is on product page");
+    }
+
+
+    @When("the user clicks the Add to Cart button")
+    public void userClicksAddToCartButton() throws InterruptedException {
+        Thread.sleep(2000);
+        WebElement addToCartButton = driver.findElement(By.xpath("//*[@id=\"main\"]/div[2]/div/div/button"));
+
+        //((JavascriptExecutor) driver).executeScript("window.scrollTo(0,"+addToCartButton.getLocation().y+")");
```
Comment (ib222dp) [inline src/test/java/CheckWebshopStepDefinition.java]: You can remove this commented out line

**Review by ib222dp — CHANGES_REQUESTED** [review]

**Review by ib222dp — APPROVED** [review]

**Review by ipajen — APPROVED** [review]

**Comment by ipajen** [comment]
the topic should be changed from " written test for the issue anf it is failing #32" to what it does..
